# Generated by Django 5.2 on 2025-04-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin Bimbel'), ('siswa', 'Siswa')], default='siswa', max_length=10),
        ),
    ]
